export const NIGERIAN_BANKS = [
  // Commercial Banks
  { name: "Access Bank", code: "044" },
  { name: "Citibank Nigeria", code: "023" },
  { name: "Ecobank Nigeria", code: "050" },
  { name: "Fidelity Bank", code: "070" },
  { name: "First Bank of Nigeria", code: "011" },
  { name: "First City Monument Bank (FCMB)", code: "214" },
  { name: "Globus Bank", code: "00103" },
  { name: "Guaranty Trust Bank (GTBank)", code: "058" },
  { name: "Heritage Bank", code: "030" },
  { name: "Keystone Bank", code: "082" },
  { name: "Optimus Bank", code: "00107" },
  { name: "Polaris Bank", code: "076" },
  { name: "Providus Bank", code: "101" },
  { name: "Stanbic IBTC Bank", code: "221" },
  { name: "Standard Chartered Bank Nigeria", code: "068" },
  { name: "Sterling Bank", code: "232" },
  { name: "SunTrust Bank", code: "100" },
  { name: "Union Bank of Nigeria", code: "032" },
  { name: "United Bank for Africa (UBA)", code: "033" },
  { name: "Unity Bank", code: "215" },
  { name: "Wema Bank", code: "035" },
  { name: "Zenith Bank", code: "057" },

  // Digital / Fintech / MFBs
  { name: "ALAT by Wema", code: "035A" },
  { name: "Carbon", code: "565" },
  { name: "FairMoney Microfinance Bank", code: "51318" },
  { name: "Flutterwave Barter", code: "110002" },
  { name: "GoMoney", code: "100022" },
  { name: "Kuda Bank", code: "50211" },
  { name: "Moniepoint Microfinance Bank", code: "50515" },
  { name: "Opay", code: "999992" },
  { name: "PalmPay", code: "999991" },
  { name: "Paystack-Titan", code: "100039" },
  { name: "Rubies Bank", code: "125" },
  { name: "Sparkle Microfinance Bank", code: "51310" },
  { name: "Titan Trust Bank", code: "102" },
  { name: "VFD Microfinance Bank", code: "566" },
];
