name = "pambaadverts"
main = ".open-next/worker.js"
compatibility_date = "2026-06-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true

[build]
command = "npm run build:cf"
